name: testtodo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ">=2.13.0"

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.24.2

  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  google_fonts: ^6.1.0
  intl: ^0.19.0
  fluttertoast: ^8.2.4

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

